// BLite.Server — BLite.Sample
// Copyright (C) 2026 Luca Fabbri — AGPL-3.0
//
// Minimal Products CRUD API that shows how to use BLite.Client
// with a typed DocumentDbContext (ProductCatalogContext) and
// LINQ-based queries via IBLiteQueryable<Product>.
//
// Endpoints:
//   POST   /products            → insert a new product
//   GET    /products            → list (with optional activeOnly / limit)
//   GET    /products/changes    → SSE stream of change events (Watch)
//   GET    /products/{id}       → get one product by ObjectId
//   PUT    /products/{id}       → update fields (omit unchanged)
//   DELETE /products/{id}       → remove by ObjectId
//   POST   /products/search     → typed LINQ search with filter, sort, paging

using System.Text.Json;
using System.Threading.Channels;
using BLite.Bson;
using BLite.Client;
using BLite.Client.Collections;
using BLite.Core.CDC;
using BLite.Core.Query;
using BLite.Sample;
using Microsoft.AspNetCore.Http.HttpResults;
using Scalar.AspNetCore;

// ── Builder ───────────────────────────────────────────────────────────────────

var builder = WebApplication.CreateBuilder(args);

// BLiteClient is a singleton — reuse the GrpcChannel across all requests.
builder.Services.AddSingleton(sp =>
{
    var opts = builder.Configuration
        .GetSection("BLite")
        .Get<BLiteClientOptions>()
        ?? throw new InvalidOperationException(
            "Missing 'BLite' configuration section in appsettings.json. " +
            "Set Host, Port, ApiKey and UseTls.");
    return new BLiteClient(opts);
});

// ProductCatalogContext is generated by the source generators.
// Its constructor accepts a BLiteClient and wires up remote collections.
builder.Services.AddSingleton(sp =>
    new ProductCatalogContext(sp.GetRequiredService<BLiteClient>()));

builder.Services.AddOpenApi();

// ── App ───────────────────────────────────────────────────────────────────────

var app = builder.Build();

app.MapOpenApi();                          // /openapi/v1.json
app.MapScalarApiReference(options =>
{
    options.Title = "BLite Sample — Products API";
});                                        // /scalar/v1

// ── Mapping helpers ───────────────────────────────────────────────────────────

static bool TryParseObjectId(string hex, out ObjectId id)
{
    if (hex.Length == 24)
    {
        try
        {
            id = new ObjectId(Convert.FromHexString(hex));
            return true;
        }
        catch { /* invalid bytes */ }
    }
    id = default;
    return false;
}

static ProductResponse ToResponse(Product p) =>
    new(p.Id.ToString(), p.Name, p.Category, p.Price, p.Stock, p.Active, p.CreatedAt);

// ── POST /products ────────────────────────────────────────────────────────────

app.MapPost("/products", async Task<Created<ProductIdResponse>> (
    CreateProductRequest req,
    ProductCatalogContext db,
    CancellationToken ct) =>
{
    var product = new Product
    {
        Id        = ObjectId.NewObjectId(),
        Name      = req.Name,
        Category  = req.Category,
        Price     = req.Price,
        Stock     = req.Stock,
        Active    = req.Active,
        CreatedAt = DateTime.UtcNow
    };
    var id = await db.Products.InsertAsync(product, ct);
    return TypedResults.Created($"/products/{id}", new ProductIdResponse(id.ToString()));
})
.WithName("CreateProduct")
.WithSummary("Insert a new product into the catalog.")
.WithTags("Products");

// ── GET /products ─────────────────────────────────────────────────────────────

app.MapGet("/products", async Task<Ok<List<ProductResponse>>> (
    int?  limit,
    bool? activeOnly,
    ProductCatalogContext db,
    CancellationToken ct) =>
{
    var cap   = Math.Min(limit ?? 50, 500);
    var query = db.Products.AsQueryable();
    if (activeOnly ?? true)
        query = query.Where(p => p.Active);
    var list = await query.Take(cap).ToListAsync(ct);
    return TypedResults.Ok(list.Select(ToResponse).ToList());
})
.WithName("ListProducts")
.WithSummary("Return up to 'limit' products (default 50, max 500).")
.WithTags("Products");

// ── GET /products/changes ─────────────────────────────────────────────────────

app.MapGet("/products/changes", async (
    bool?             capturePayload,
    ProductCatalogContext db,
    HttpContext       ctx,
    CancellationToken ct) =>
{
    ctx.Response.ContentType = "text/event-stream";
    ctx.Response.Headers.CacheControl = "no-cache";

    var channel = Channel.CreateUnbounded<ChangeStreamEvent<ObjectId, Product>>();
    using var sub = db.Products.Watch(capturePayload ?? true)
        .Subscribe(e => channel.Writer.TryWrite(e));

    await foreach (var e in channel.Reader.ReadAllAsync(ct))
    {
        var payload = e.Entity is not null ? ToResponse(e.Entity) : null;
        var json = JsonSerializer.Serialize(new
        {
            type      = e.Type.ToString(),
            id        = e.DocumentId.ToString(),
            timestamp = e.Timestamp,
            product   = payload
        });
        await ctx.Response.WriteAsync($"data: {json}\n\n", ct);
        await ctx.Response.Body.FlushAsync(ct);
    }
})
.WithName("WatchProducts")
.WithSummary("SSE stream of product change events (insert/update/delete).")
.WithTags("Products");

// ── GET /products/{id} ────────────────────────────────────────────────────────

app.MapGet("/products/{id}", async Task<Results<Ok<ProductResponse>, NotFound, BadRequest<string>>> (
    string id,
    ProductCatalogContext db,
    CancellationToken ct) =>
{
    if (!TryParseObjectId(id, out var objId))
        return TypedResults.BadRequest("'id' must be a 24-char lowercase hex ObjectId.");

    var product = await db.Products.FindByIdAsync(objId, ct);
    return product is not null
        ? TypedResults.Ok(ToResponse(product))
        : (Results<Ok<ProductResponse>, NotFound, BadRequest<string>>)TypedResults.NotFound();
})
.WithName("GetProduct")
.WithSummary("Find a product by its ObjectId.")
.WithTags("Products");

// ── PUT /products/{id} ────────────────────────────────────────────────────────

app.MapPut("/products/{id}", async Task<Results<Ok<ProductIdResponse>, NotFound, BadRequest<string>>> (
    string id,
    UpdateProductRequest req,
    ProductCatalogContext db,
    CancellationToken ct) =>
{
    if (!TryParseObjectId(id, out var objId))
        return TypedResults.BadRequest("'id' must be a 24-char lowercase hex ObjectId.");

    var current = await db.Products.FindByIdAsync(objId, ct);
    if (current is null)
        return TypedResults.NotFound();

    if (req.Name     is not null) current.Name     = req.Name;
    if (req.Category is not null) current.Category = req.Category;
    if (req.Price    is not null) current.Price    = req.Price.Value;
    if (req.Stock    is not null) current.Stock    = req.Stock.Value;
    if (req.Active   is not null) current.Active   = req.Active.Value;

    await db.Products.UpdateAsync(current, ct);
    return TypedResults.Ok(new ProductIdResponse(id));
})
.WithName("UpdateProduct")
.WithSummary("Update fields of an existing product (omit unchanged fields).")
.WithTags("Products");

// ── DELETE /products/{id} ─────────────────────────────────────────────────────

app.MapDelete("/products/{id}", async Task<Results<Ok<DeletedResponse>, NotFound, BadRequest<string>>> (
    string id,
    ProductCatalogContext db,
    CancellationToken ct) =>
{
    if (!TryParseObjectId(id, out var objId))
        return TypedResults.BadRequest("'id' must be a 24-char lowercase hex ObjectId.");

    var ok = await db.Products.DeleteAsync(objId, ct);
    return ok
        ? TypedResults.Ok(new DeletedResponse(id))
        : (Results<Ok<DeletedResponse>, NotFound, BadRequest<string>>)TypedResults.NotFound();
})
.WithName("DeleteProduct")
.WithSummary("Delete a product by its ObjectId.")
.WithTags("Products");

// ── POST /products/search ─────────────────────────────────────────────────────

app.MapPost("/products/search", async Task<Ok<List<ProductResponse>>> (
    SearchRequest req,
    ProductCatalogContext db,
    CancellationToken ct) =>
{
    var query = db.Products.AsQueryable();

    if (req.Category is not null)
        query = query.Where(p => p.Category == req.Category);
    if (req.MinPrice is not null)
        query = query.Where(p => p.Price >= req.MinPrice.Value);
    if (req.MaxPrice is not null)
        query = query.Where(p => p.Price <= req.MaxPrice.Value);
    if (req.ActiveOnly ?? false)
        query = query.Where(p => p.Active);

    query = (req.OrderBy?.ToLowerInvariant(), req.Descending ?? false) switch
    {
        ("price",     false) => query.OrderBy(p => p.Price),
        ("price",     true)  => query.OrderByDescending(p => p.Price),
        ("name",      false) => query.OrderBy(p => p.Name),
        ("name",      true)  => query.OrderByDescending(p => p.Name),
        ("stock",     false) => query.OrderBy(p => p.Stock),
        ("stock",     true)  => query.OrderByDescending(p => p.Stock),
        ("createdat", false) => query.OrderBy(p => p.CreatedAt),
        ("createdat", true)  => query.OrderByDescending(p => p.CreatedAt),
        _                    => query
    };

    if (req.Skip is > 0) query = query.Skip(req.Skip.Value);
    query = query.Take(Math.Min(req.Take ?? 50, 500));

    var list = await query.ToListAsync(ct);
    return TypedResults.Ok(list.Select(ToResponse).ToList());
})
.WithName("SearchProducts")
.WithSummary("Filter, sort and page products with typed LINQ.")
.WithDescription("""
    All fields are optional.

    Example body:
    {
      "category":   "electronics",
      "minPrice":   100,
      "maxPrice":   500,
      "activeOnly": true,
      "orderBy":    "price",
      "descending": false,
      "skip":       0,
      "take":       20
    }
    """)
.WithTags("Products");

// ── Run ───────────────────────────────────────────────────────────────────────

app.Run();

// ── Response models ───────────────────────────────────────────────────────────

record ProductResponse(
    string   Id,
    string   Name,
    string   Category,
    double   Price,
    int      Stock,
    bool     Active,
    DateTime CreatedAt);

record ProductIdResponse(string Id);

record DeletedResponse(string Id);

// ── Request models ────────────────────────────────────────────────────────────

record CreateProductRequest(
    string Name,
    string Category,
    double Price,
    int    Stock,
    bool   Active = true);

record UpdateProductRequest(
    string?  Name     = null,
    string?  Category = null,
    double?  Price    = null,
    int?     Stock    = null,
    bool?    Active   = null);

record SearchRequest(
    string?  Category   = null,
    double?  MinPrice   = null,
    double?  MaxPrice   = null,
    bool?    ActiveOnly = null,
    string?  OrderBy    = null,
    bool?    Descending = null,
    int?     Skip       = null,
    int?     Take       = null);


