<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>BLite.Proto</RootNamespace>
    <AssemblyName>BLite.Proto</AssemblyName>

    <Version>0.2.1</Version>
    <AssemblyVersion>0.1.4.0</AssemblyVersion>
    <FileVersion>0.1.4.0</FileVersion>
    <Authors>BLite Team</Authors>
    <Company>EntglDb</Company>
    <Copyright>Copyright © 2026 Luca Fabbri</Copyright>
    <Description>Protobuf contracts and generated gRPC stubs for BLite Server.</Description>
    <RepositoryUrl>https://github.com/EntglDb/BLite.Server</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>AGPL-3.0-only</PackageLicenseExpression>
  </PropertyGroup>

  <!-- protoc + gRPC codegen -->
  <ItemGroup>
    <Protobuf Include="Protos\blite.proto" GrpcServices="Both" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.34.1" />
    <PackageReference Include="Grpc.Core.Api" Version="2.76.0" />
    <PackageReference Include="Grpc.Tools" Version="2.78.0" PrivateAssets="All" />
    <PackageReference Include="MessagePack" Version="3.1.*" />
    <PackageReference Include="MessagePack.Annotations" Version="3.1.*" />
  </ItemGroup>

</Project>
