// BLite.Client.SourceGenerators — RemoteContextGenerator
// Copyright (C) 2026 Luca Fabbri — AGPL-3.0
//
// For each partial class inheriting from DocumentDbContext, generates:
//   - A _remoteClient backing field
//   - A public constructor accepting BLiteClient
//   - A CreateCollection<TId,T> override that delegates to BLiteClient.GetDocumentCollection

using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BLite.Client.SourceGenerators;

[Generator]
public sealed class RemoteContextGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var pipeline = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsPotentialDbContext(node),
                transform: static (ctx, _) => GetContextInfo(ctx))
            .Where(static info => info is not null)
            .Collect()
            // De-duplicate by full class name (multiple partial declarations map to the same type)
            .SelectMany(static (items, _) =>
                items.GroupBy(static i => i!.FullName).Select(static g => g.First()));

        context.RegisterSourceOutput(pipeline, static (spc, info) =>
        {
            if (info is null) return;
            spc.AddSource($"{info.FullName}.RemoteContext.g.cs", Emit(info!));
        });
    }

    // ── Syntax predicate ─────────────────────────────────────────────────────

    private static bool IsPotentialDbContext(SyntaxNode node)
    {
        // Skip already-generated files
        if (node.SyntaxTree.FilePath.EndsWith(".g.cs")) return false;

        return node is ClassDeclarationSyntax cls
            && cls.BaseList is { Types.Count: > 0 }
            && cls.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword));
    }

    // ── Semantic transform ───────────────────────────────────────────────────

    private static ContextInfo? GetContextInfo(GeneratorSyntaxContext ctx)
    {
        var cls = (ClassDeclarationSyntax)ctx.Node;
        if (ctx.SemanticModel.GetDeclaredSymbol(cls) is not INamedTypeSymbol symbol)
            return null;

        if (!InheritsFromDocumentDbContext(symbol))
            return null;

        return new ContextInfo
        {
            Name = symbol.Name,
            Namespace = symbol.ContainingNamespace?.ToDisplayString() ?? "",
            FullName = symbol.ToDisplayString()
        };
    }

    private static bool InheritsFromDocumentDbContext(INamedTypeSymbol symbol)
    {
        var current = symbol.BaseType;
        while (current is not null)
        {
            if (current.Name == "DocumentDbContext")
                return true;
            current = current.BaseType;
        }
        return false;
    }

    // ── Code emission ─────────────────────────────────────────────────────────

    private static string Emit(ContextInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {info.Namespace}");
        sb.AppendLine("{");
        sb.AppendLine($"    public partial class {info.Name}");
        sb.AppendLine("    {");

        // Backing field — intentionally prefixed to minimise collision risk
        sb.AppendLine("        private global::BLite.Client.BLiteClient? _remoteClient;");
        sb.AppendLine();

        // Constructor
        sb.AppendLine($"        public {info.Name}(global::BLite.Client.BLiteClient client) : base()");
        sb.AppendLine("        {");
        sb.AppendLine("            _remoteClient = client;");
        // base() already called InitializeCollections() with _remoteClient == null (no-op path).
        // Call it again now that the client is available so all collection properties are set.
        sb.AppendLine("            InitializeCollections();");
        sb.AppendLine("        }");
        sb.AppendLine();

        // CreateCollection override
        sb.AppendLine("        protected override global::BLite.Core.Collections.IDocumentCollection<TId, T>");
        sb.AppendLine("            CreateCollection<TId, T>(global::BLite.Core.Collections.IDocumentMapper<TId, T> mapper)");
        sb.AppendLine("            where T : class");
        sb.AppendLine("        {");
        // Guard: called too early from the base ctor before _remoteClient is set
        sb.AppendLine("            if (_remoteClient is null) return null!;");
        sb.AppendLine("            return _remoteClient.GetDocumentCollection<TId, T>(mapper);");
        sb.AppendLine("        }");

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    // ── Model ─────────────────────────────────────────────────────────────────

    private sealed class ContextInfo
    {
        public string Name { get; set; } = "";
        public string Namespace { get; set; } = "";
        public string FullName { get; set; } = "";
    }
}
