// BLite.Client.IntegrationTests — IndexManagementTests
// Copyright (C) 2026 Luca Fabbri — AGPL-3.0
//
// End-to-end tests for CreateIndex (BTree / Vector / Spatial),
// DropIndex, and ListIndexes.

using BLite.Client.IntegrationTests.Infrastructure;

namespace BLite.Client.IntegrationTests;

[Collection("Integration")]
public class IndexManagementTests : IntegrationTestBase
{
    public IndexManagementTests(BLiteServerFixture fixture) : base(fixture) { }

    // ── BTree index ───────────────────────────────────────────────────────────

    [Fact]
    public async Task CreateBTreeIndex_ListIndexes_ContainsIndex()
    {
        await using var client = CreateClient();
        var col = client.GetDynamicCollection(UniqueCollection());
        var doc = await col.NewDocumentAsync(["email"], b => b.AddString("email", "a@b.com"));
        await col.InsertAsync(doc);

        await col.CreateIndexAsync("email", name: "idx_email");

        var indexes = await col.ListIndexesAsync();
        var idx = Assert.Single(indexes, i => i.Name == "idx_email");
        Assert.Equal("email", idx.FieldPath);
        Assert.Equal("BTree", idx.Type);
    }

    [Fact]
    public async Task CreateBTreeIndex_Unique_RejectedDuplicateValue()
    {
        await using var client = CreateClient();
        var col = client.GetDynamicCollection(UniqueCollection());
        _ = await col.NewDocumentAsync(["email"], _ => { });

        var d1 = await col.NewDocumentAsync(["email"], b => b.AddString("email", "dup@test.com"));
        await col.InsertAsync(d1);

        await col.CreateIndexAsync("email", unique: true);

        var d2 = await col.NewDocumentAsync(["email"], b => b.AddString("email", "dup@test.com"));
        await Assert.ThrowsAsync<InvalidOperationException>(() => col.InsertAsync(d2));
    }

    [Fact]
    public async Task CreateBTreeIndex_AutoGeneratedName_AppearsInList()
    {
        await using var client = CreateClient();
        var col = client.GetDynamicCollection(UniqueCollection());

        await col.CreateIndexAsync("category");

        var indexes = await col.ListIndexesAsync();
        Assert.Contains(indexes, i => i.FieldPath == "category" && i.Type == "BTree");
    }

    // ── Vector index ──────────────────────────────────────────────────────────

    [Fact]
    public async Task CreateVectorIndex_ListIndexes_ShowsCorrectMetadata()
    {
        await using var client = CreateClient();
        var col = client.GetDynamicCollection(UniqueCollection());

        await col.CreateVectorIndexAsync("embedding", dimensions: 8, metric: "Cosine", name: "idx_vec");

        var indexes = await col.ListIndexesAsync();
        var idx = Assert.Single(indexes, i => i.Name == "idx_vec");
        Assert.Equal("Vector", idx.Type);
        Assert.Equal(8, idx.Dimensions);
        Assert.Equal("Cosine", idx.Metric);
    }

    [Theory]
    [InlineData("Cosine")]
    [InlineData("L2")]
    [InlineData("DotProduct")]
    public async Task CreateVectorIndex_AllMetrics_Accepted(string metric)
    {
        await using var client = CreateClient();
        var col = client.GetDynamicCollection(UniqueCollection());

        await col.CreateVectorIndexAsync("vec", dimensions: 4, metric: metric);

        var indexes = await col.ListIndexesAsync();
        Assert.Contains(indexes, i => i.Type == "Vector" && i.Metric == metric);
    }

    // ── Spatial index ─────────────────────────────────────────────────────────

    [Fact]
    public async Task CreateSpatialIndex_ListIndexes_ShowsSpatialType()
    {
        await using var client = CreateClient();
        var col = client.GetDynamicCollection(UniqueCollection());

        await col.CreateSpatialIndexAsync("location", name: "idx_geo");

        var indexes = await col.ListIndexesAsync();
        var idx = Assert.Single(indexes, i => i.Name == "idx_geo");
        Assert.Equal("Spatial", idx.Type);
        Assert.Equal("location", idx.FieldPath);
    }

    [Fact]
    public async Task CreateSpatialIndex_AutoGeneratedName_AppearsInList()
    {
        await using var client = CreateClient();
        var col = client.GetDynamicCollection(UniqueCollection());

        await col.CreateSpatialIndexAsync("coords");

        var indexes = await col.ListIndexesAsync();
        Assert.Contains(indexes, i => i.FieldPath == "coords" && i.Type == "Spatial");
    }

    // ── DropIndex ─────────────────────────────────────────────────────────────

    [Fact]
    public async Task DropIndex_ExistingIndex_ReturnsTrueAndRemoves()
    {
        await using var client = CreateClient();
        var col = client.GetDynamicCollection(UniqueCollection());
        await col.CreateIndexAsync("field1", name: "idx_to_drop");

        var ok = await col.DropIndexAsync("idx_to_drop");

        Assert.True(ok);
        var indexes = await col.ListIndexesAsync();
        Assert.DoesNotContain(indexes, i => i.Name == "idx_to_drop");
    }

    [Fact]
    public async Task DropIndex_NonExistent_ReturnsFalse()
    {
        await using var client = CreateClient();
        var col = client.GetDynamicCollection(UniqueCollection());

        var ok = await col.DropIndexAsync("nonexistent_index");

        Assert.False(ok);
    }

    // ── ListIndexes ───────────────────────────────────────────────────────────

    [Fact]
    public async Task ListIndexes_NoSecondaryIndexes_ReturnsEmptyList()
    {
        await using var client = CreateClient();
        var col = client.GetDynamicCollection(UniqueCollection());

        var indexes = await col.ListIndexesAsync();

        Assert.Empty(indexes);
    }

    [Fact]
    public async Task ListIndexes_MultipleIndexes_AllListed()
    {
        await using var client = CreateClient();
        var col = client.GetDynamicCollection(UniqueCollection());

        await col.CreateIndexAsync("name",   name: "idx_name");
        await col.CreateIndexAsync("status", name: "idx_status");

        var indexes = await col.ListIndexesAsync();
        Assert.Contains(indexes, i => i.Name == "idx_name");
        Assert.Contains(indexes, i => i.Name == "idx_status");
    }
}
